### ISSUE TITLE
project status?

### ISSUE THREAD

**Issue by jmdyck** [NYPL/catalog_of_copyright_entries_project#43]
Could you add a 'status' section to the README? It looks like the work's all done, and yet there are open issues.

**Comment by seanredmond** [comment]
Good idea, I will add one.

**Comment by drorm** [comment]
Also, can you point to the database or files off titles that are now in the public domain?

**Comment by jmdyck** [comment]
It's been 3 years since I asked, and still no 'status' section in the README. Which makes me think the project status is "mostly dead".

**Comment by gregcram** [comment]
@drorm Although we don't keep a list of titles that are in the public domain, we have built an experimental search interface you can use to [match registrations with renewals](https://cce-search.nypl.org). This search interface is currently limited to books as we seek out additional funding.

@jmdyck I added a project status section to the readme (82da829). We continue to pursue funding opportunities to tackle the next tranche of records.

**Comment by drorm** [comment]
Thank you.

**Comment by jmdyck** [comment]
Thanks, good to hear.
