### ISSUE TITLE
Handle renewals in the registrations

### ISSUE THREAD

**Issue by seanredmond** [NYPL/catalog_of_copyright_entries_project#48]
There are two versions of this: 1) Registrations that are their own renewals and 2) renewals that are in the registrations for some reason.

An example of the first is A1053002, being registered for the first time, just under the deadline to renew it:

    KENT, FRANK R. Political behavior: the heretofore unwritten laws, customs and principles of
    politics as practiced in the United States. © 23Aug28; A1053002. Frank R. Kent (A); 
    28Oct55; R158303.

Of the second is on pg 1507 of 1960 No. 2

![Screen Shot 2019-08-16 at 11 45 05 AM](https://user-images.githubusercontent.com/720703/63180707-d5cb5280-c01c-11e9-9854-2d7d75387ddf.png)

The second entry is just the renewal for A58707. Why it is in the registrations and not the renewals pages of the volume, I don't know.

The solution for both is probably to add a `<renewalEntry>` element that can be a child of `<copyrightEntries>`, `<entryGroup>`, or a single `<copyrightEntry>`

**Comment by gregcram** [comment]
As we move beyond books and into other formats, we'll need to account for
renewals in the DTD. Perhaps this is an opportunity to add a few elements
on renewals, or this might be a unique situation that doesn't call for our
focus on renewal DTDs.

**Comment by zvisrosen** [comment]
I was told by the Copyright Office that getting renewals and registrations in the same envelope was not unheard of, especially in 2005 (I think people misunderstood the end of renewal and renewal).  

It looks like the first one was an example of that, but I don't think it is.  The XXC series ended October 13, 1928, and a book registered in August of 1928 would have almost exactly that registration number.  Indeed, it was registered timely (which makes sense - the Washingtonian decision was still over a decade away - the card catalog confirms this: https://cdn.loc.gov/service/copyright/hprcatcard/18/98/19/37/KE/NT/-K/ES/E/18981937KENT-KESE/18981937KENT-KESE0123.jpg

For the Niebuhr example I suspect they filed the renewal of the first edition and registration in the newest edition in the same envelope.  Why they chose to catalog it that way?  No clue.

**Comment by seanredmond** [comment]
@zvisrosen you are proven right, because A1053002 actually _is_ in the 1928 volume (I didn't find it at first because of a now fixed typo). Turns out this is a bad example of register + renew since it's just a renewal in with the registrations, like the Niebuhr entry. Maybe they all are? We didn't account for this so the XML is a bit messy for these entries.

**Comment by seanredmond** [comment]
These are templates how I'm thinking to handle this.

## Simplest Case
![Screen Shot 2019-08-20 at 11 49 32 AM](https://user-images.githubusercontent.com/720703/63365569-e134bb80-c345-11e9-98e2-3e3a2c07319a.png)

    <renewalEntry id="8BDBF399-728D-1014-8500-D70EB891A161">
      <author><authorName>ADAMS, HERBERT.</authorName></author>
      <title>The queen's gate mystery.</title>
      <renewal>
        <registrations> &#x000A9;
          <registration><regDate date="1927-07-08">8Jul27</regDate>; <regNum num="A000999664">A999664</regNum></registration>.
        </registrations>
        <claimant><claimantName>Herbert Adams</claimantName> (<claimantClass>A</claimantClass>)</claimant>; 
        <renewalDate date="1955-04-28">28Apr55</renewalDate>; <renewalNum num="R000149031">R149031</renewalNum>
      </renewal>
    </renewalEntry>

## Interim + Regular Registration

![Screen Shot 2019-08-20 at 11 46 23 AM](https://user-images.githubusercontent.com/720703/63366017-d6c6f180-c346-11e9-9399-68a8918ba6f2.png)

    <renewalEntry id="51CBFDE3-72C4-1014-84F6-87703AD4166D">
      <author><authorName>SCOTT, WINIFRED MARY.</authorName></author>
      <title>The last days of September</title>,
      <author><role>by</role> <authorName>Pamela Wynne</authorName>, <role>pseud.</role> </author>
      <renewal>
        <registrations> ©
          <registration><regDate date="1931-05-19">19May31</regDate>, <regNum num="AI000015224">AI-15224</regNum></registration>;
          <registration><regDate date="1931-08-06">6Aug31</regDate>, <regNum num="A000041100">A41100</regNum></registration>.
        </registrations>
        <claimant><claimantName>Winifred Mary Scott</claimantName> (<claimantClass>A</claimantClass>)</claimant>; 
        <renewalDate date="1958-08-17">17Aug58</renewalDate>; <renewalNum num="R000219440">R219440</renewalNum>
      </renewal>.
    </renewalEntry>

## Multiple Renewals in One

![Screen Shot 2019-08-20 at 11 47 16 AM](https://user-images.githubusercontent.com/720703/63366055-e6ded100-c346-11e9-91d9-021203266648.png)

    <renewalEntry id="53727901-72C4-1014-84F6-87703AD4166D">
      <title>STREET &amp; SMITH'S TOP NOTCH MAGAZINE.</title>
      © <claimant><claimantName>Street &amp; Smith Publications, Inc.</claimantName> (<claimantClass>PCW</claimanClass>)<claimant> <vol>v.86, no. 3-6, July 1-Aug. 15, 1931</vol>.
      <renewal>
        <registrations> ©
          <registration renewal_num="R000218020" renewal_date="1958-07-16"><regDate date="1931-05-29">29May31</regDate>, <regNum>B116123</regNum></registration>;
          <registration renewal_num="R000218021" renewal_date="1958-07-16"><regDate date="1931-06-17">17Jun31</regDate>, <regNum>B118058</regNum></registration>;
          <registration renewal_num="R000218022" renewal_date="1958-07-16"><regDate date="1931-07-01">1Jul31</regDate>, <regNum>B118953</regNum></registration>;
          <registration renewal_num="R000218023" renewal_date="1958-07-16"><regDate date="1931-07-15">15Jul31</regDate>, <regNum>B121578</regNum></registration>.
        </registrations>
        <regDate date="1958-07-16">16Jul58</regDate>; <regNum num="R000218020 R000218021 R000218022 R000218023">R218020-218023</regNum>.
      </renewal>
    </renewalEntry>

These are common cases in the renewals proper. The granularity (`<registrations>`/`<registration>`) may seem like overkill in the first example, but one thing we've learned is how many dates and ids can be stuffed into a single entry and complicated it can be to figure out which go with which.

I've also thrown in some potential global changes:

* normalizing the ids to the same format used by the copyright office database
* making the normalization an attribute of the number element rather than the top element of the entry as we've been doing with `copyrightEntry`.

**Comment by zvisrosen** [comment]
This looks really great!  I approve of having a robust system like this that's flexible enough for complicated situations.

Ad interim copyright was a funny system, whereby you needed to file for ad interim upon publication of a book in the English language abroad, and publish (and re-register) within four months in the United States from type set in the United States  (Until 1922 it was only one month).  Robert Spoo has written about how this rule proved problematic for authors like James Joyce, who could not easily find publishers in the United States due to concerns of criminal obscenity prosecutions.

Failure to comply with ad interim meant you lost your US copyright protection, but most authors got it back with the Uruguay Round / restoration.

**Comment by seanredmond** [comment]
Fixed as of v2.2
